#!/bin/bash
SECRET=$(kubectl get secret password --output json)

# Check if we have a result
if [ $? == 1 ]; then
  echo "FAIL: There was no secret called password"
  exit 1
fi

PASSWORD=$(echo $SECRET | jq -r '.data[]' | base64 -d)
if [ "$PASSWORD" != "MyPassword1!" ]; then
  echo "FAIL: The value is incorrect. Expected password MyPassword1!"
  exit 1
fi

exit 0