#!/bin/bash
cat > /root/nginx.yml <<EOF
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.13.8-alpine
    env:
    - name: MYSECRET
      value: changeme
    ports:
    - containerPort: 80
EOF

kubectl create secret generic secretenv --from-literal=envkey=thisIsAnEnvVar