#!/bin/bash
# Check if secret is created
COMMAND=$(cat /root/.bash_history | grep -e "^kubectl apply -f secret.yml" -e "^kubectl create -f secret.yml" | wc -l)
if [ $COMMAND -eq 0 ]; then
  echo "FAIL: kubectl was not used to create the secret from the definition file"
  exit 1
fi

SECRET=$(kubectl get secret mysecret --output json)

# Check if we have a result
if [ $? == 1 ]; then
  echo "FAIL: The secret was not succesfully created"
  exit 1
fi

PASSWORD=$(echo $SECRET | jq -r '.data.mysecret')
if [ "$PASSWORD" != "TmV3UGFzc3dvcmQyIQ==" ]; then
  echo "FAIL: The encoded value is incorrect. Make sure it does not contain a newline character"
  exit 1
fi

exit 0